name: Validate Commit Messages

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Fetch base branch
        run: git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}

      - name: Set up shell
        run: |
          sudo apt-get update
          sudo apt-get install -y git

      - name: Run commit message validation
        env:
          GITHUB_BASE_REF: ${{ github.event.pull_request.base.sha }}
        run: |
          chmod +x ./.validate_commit.sh
          ./.validate_commit.sh
